import Head from "next/head";
import "bootstrap/dist/css/bootstrap.css";
import "animate.css";

import Banner from "../components/Banner";
import styles from "../styles/Home.module.css";
import WhatIDo from "../components/WhatIDo";
import ContactMe from "../components/ContactMe";
import Footer from "../components/Footer";
import MyWorks from "../components/MyWorks";
import About from "../components/About";
import NavBar from "../components/NavBar";
import NavProvider from "../context/NavContext";

export default function Home() {
  return (
    <div className="position-relative">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="css/font-awesome.min.css" />
        <script src="https://use.fontawesome.com/96ee2bc964.js"></script>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
          integrity="sha512-c42qTSw/wPZ3/5LBzD+Bw5f7bSF2oxou6wEb+I/lqeaKV5FDIfMvvRp772y4jcJLKuGUOpbJMdg/BTl50fJYAw=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        />
        <script
          src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"
          integrity="sha512-Eak/29OTpb36LLo2r47IpVzPBLXnAMPAVypbSZiZ4Qkf8p/7S/XRG5xp7OKWPPYfJT6metI+IORkR5G8F900+g=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        />
        <script
          src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"
          integrity="sha512-Eak/29OTpb36LLo2r47IpVzPBLXnAMPAVypbSZiZ4Qkf8p/7S/XRG5xp7OKWPPYfJT6metI+IORkR5G8F900+g=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        ></script>
      </Head>
      <>
        <NavProvider>
          <NavBar />
          <Banner />
          {/* <WhatIDo /> */}
          <About />
          <MyWorks />
          <ContactMe />
          <Footer />
        </NavProvider>
      </>
    </div>
  );
}
